QE-7883 - Check for batch settings.

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,8 +1,6 @@
 name: CI
 
 on:
-  pull_request:
-    types: [opened, edited, reopened, synchronize]
   push:
     branches:
       - '**'
@@ -19,32 +17,25 @@ jobs:
   run-tests:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Log Git SHA
-        run: echo "$GITHUB_SHA"
-      - name: Use Node.js
-        uses: actions/setup-node@v1
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v1
         with:
           node-version: '14.x'
+      - run: echo "$GITHUB_SHA"
       - run: npm ci
       - run: npm run eyes:setup
-      - name: Run Tests
-        run: npm run cypress:run
+      - run: npm run cypress:run
     
   batch-completion-notification:
     needs: run-tests
     if: always()
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout2
-        uses: actions/checkout@v2
-      - name: Update Applitools batch status 
-        uses: ./.github/actions/
+      - uses: actions/checkout@v2
+      - uses: ./.github/actions/
         id: notify
         with:
           batch-id: ${{ env.APPLITOOLS_BATCH_ID }}
           api-key: ${{ env.APPLITOOLS_API_KEY }}
           applitools-server-url: ${{ env.APPLITOOLS_SERVER_URL }}
-      - name: Get the Applitools response
-        run: if [[ ${{ steps.notify.outputs.response }} == '200' ]]; then echo "HTTP 200 OK received"; else echo "Error code received."; exit 1; fi
+      - run: if [[ ${{ steps.notify.outputs.response }} == '200' ]]; then echo "HTTP 200 OK received"; else echo "Error code received."; exit 1; fi
